frontend:
  - changed-files:
      - any-glob-to-any-file: ["frontend-cal/**"]

backend:
  - changed-files:
      - any-glob-to-any-file: ["backend/**"]

devops:
  - changed-files:
      - any-glob-to-any-file:
        - ".github/**"
        - "**/.devcontainer/**"
        - "dev/**"

docs:
  - changed-files:
      - any-glob-to-any-file:
        - "**/README.md"
        - "**/docs/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
        - "frontend-cal/package*.json"
        - "backend/requirements.txt"