version: '3.9'

services:
  backend-ae:
    build:
      context: ..
      dockerfile: dev/Dockerfile-backend-ae
    command: npm run dev # Use `npm start` for production
    volumes:
      - ..:/app
    ports:
      - "9000:9000"
    depends_on:
      - db-ae
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db-ae:5432/ae_db
      - NODE_ENV=development
      - PORT=9000

  backend-django:
    build:
      context: ..
      dockerfile: dev/Dockerfile-backend-lmse
    command: python backend/lms_engine/manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - db-django
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db-django
      - POSTGRES_PORT=5432

  db-ae:
    image: postgres:17
    volumes:
      - postgres_data_ae:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # Different port to avoid conflict
    environment:
      - POSTGRES_DB=ae_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  db-django:
    image: postgres:17
    volumes:
      - postgres_data_django:/var/lib/postgresql/data/
    ports:
      - "5434:5432" # Different port to avoid conflict
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data_ae:
  postgres_data_django:
