name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20'  # Recommended to use LTS version
    - name: Install Dependencies
      run: npm install
    - name: Install Firebase CLI
      run: npm install -g firebase-tools
    - name: Build
      run: npm run build
    - name: Deploy to Firebase
      run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project cal-frontend
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
