name: Code Linting

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint_frontend:
    name: Frontend Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint
        run: npm run lint:css

  lint_backend:
    name: Backend Code Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend-cal/requirements.txt
          pip install flake8 black

      - name: Run flake8
        run: |
          source venv/bin/activate
          flake8 backend-cal

      - name: Run black
        run: |
          source venv/bin/activate
          black --check backend-cal